spring:
   datasource:
     url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
     username: root
     password: password 

#JPA settings 
   jpa.hibernate.ddl-auto: update


       